### ISSUE TITLE
State pages: Winner checkmark should not wrap to next line

### ISSUE THREAD

**Issue by alykat** [nprapps/elections18-graphics#111]
![image](https://user-images.githubusercontent.com/491318/45163672-e47b7980-b1be-11e8-8d1f-9976ea6bb096.png)

**Comment by mileswwatkins** [comment]
Huh, this isn't a non-breaking space thing, this seems to be styling issue. It's the `renderCandidateName` function in `/www/js/state-results.js`, where there's a `span` for the first name, a `span` for the last name, text for the party affiliation, and then an `i` tag into which a `::before` checkmark icon is attached in the CSS.

I'm not sure how to make this fix, without botching other components of this page using `inline-block` or similar; @alykat, do you think this is enough information for you to hit it now?

https://github.com/nprapps/elections18-graphics/blob/master/www/js/state-results.js#L679-L693
