### ISSUE TITLE
Certain table cells in big-board are center-aligned, creating a ragged-left text end

### ISSUE THREAD

**Issue by freejoe76** [nprapps/elections18-graphics#112]
Example (on localhost) where it looks ragged: http://localhost:8000/board-ballot/?state=ky

![screen shot 2018-09-06 at 2 23 41 pm](https://user-images.githubusercontent.com/125554/45177448-0685f380-b1e1-11e8-90e8-38440787d5ad.png)

This is what it would look like left-aligned:

![screen shot 2018-09-06 at 2 23 56 pm](https://user-images.githubusercontent.com/125554/45177463-100f5b80-b1e1-11e8-8a67-ed0265486a0e.png)

**Comment by mileswwatkins** [comment]
I'd mentioned this as a to-do in https://github.com/nprapps/elections18-graphics/issues/85#issue-351370903

**Comment by mileswwatkins** [comment]
This was caused by some style-botching on my end, as I was building something else </3
