### ISSUE TITLE
Redesign and update code for big board chamber-summary text

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#117]
In 2016, this looked like:

<img width="566" alt="screen shot 2018-09-10 at 12 58 15" src="https://user-images.githubusercontent.com/4959135/45312106-35f67200-b4f9-11e8-85ad-bd0ddcf764d5.png">

In 2018, we're making potential changes and enhancements, including:
- [x] chamber-control checkmark, and a footnote to accompany (mentioning that this _may_ be "projected") and an item in the Key
- [x] some kind of “x total pickups needed to flip control” line, to replace the "needed" column
- [x] a footnote about how the independents caucus with the Democrats, for the Senate

(Subsumes https://github.com/nprapps/elections18-graphics/issues/93 and https://github.com/nprapps/elections18-graphics/issues/115)

**Comment by alykat** [comment]
Chamber winner checkmark added to House/Senate boards.

![image](https://user-images.githubusercontent.com/491318/46848377-762a6800-cdb7-11e8-893a-7ffd64a20d12.png)

**Comment by alykat** [comment]
Related: #199

**Comment by alykat** [comment]
Added "net change" to the House and Senate boards. It has Arnie and Beth's blessing, and they don't see a need to explicitly include the # of seats needed to flip.

![image](https://user-images.githubusercontent.com/491318/47800611-026ae380-dd03-11e8-8ab5-cfd0077345a5.png)

**Comment by alykat** [comment]
Added to the Senate board:

![image](https://user-images.githubusercontent.com/491318/47820171-19292e80-dd33-11e8-9751-ef9f2863f69d.png)
