### ISSUE TITLE
Style get-caught-up graphic

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#130]
[The documentation](https://docs.google.com/document/d/1r9bTEv0xeeOoywahBUFtE2vXIuQK_vOKTSIgJTliODI) states that the only tags that the Washington Desk should use are `<i>`/`<em>`, `<b>`/`<strong>`, and `<a>`, so we'll need styles for those in the intro paragraphs and in the bullet points. Otherwise, no real surprises here.

**Comment by alykat** [comment]
Closing this b/c it overlaps with #47 and #52, and there are no plans for a standalone "get caught up" graphic.
