### ISSUE TITLE
Limit number of candidates shown in county results tables

### ISSUE THREAD

**Issue by alykat** [nprapps/elections18-graphics#133]
Because things get a _little_ crowded in Louisiana.

![image](https://user-images.githubusercontent.com/491318/45650434-46c85a00-ba9c-11e8-8954-bf7067d428b2.png)

**Comment by mileswwatkins** [comment]
Closed by https://github.com/nprapps/elections18-general/commit/38b8c4d47e87d32518d26a2bab7da949a1dddb79

**Comment by mileswwatkins** [comment]
<img width="768" alt="screen shot 2018-09-18 at 11 13 29" src="https://user-images.githubusercontent.com/4959135/45697474-e4bb3380-bb33-11e8-831b-8ae7ff5b3104.png">
