### ISSUE TITLE
State pages: Only show the board key on the "key results" tab

### ISSUE THREAD

**Issue by alykat** [nprapps/elections18-graphics#134]
It's irrelevant to all the other views.

**Comment by mileswwatkins** [comment]
<img width="756" alt="screen shot 2018-10-29 at 15 13 14" src="https://user-images.githubusercontent.com/4959135/47674209-2f958580-db8d-11e8-8e87-eeec43d730db.png">

<img width="770" alt="screen shot 2018-10-29 at 15 13 01" src="https://user-images.githubusercontent.com/4959135/47674213-31f7df80-db8d-11e8-88b2-307ca25604a1.png">

**Comment by mileswwatkins** [comment]
Shit, @alykat, it looks like we _do_ borrow some of the big-board design language, with the uppercase-plus-asterisk to indicate incumbency. What would you recommend doing here?

**Comment by alykat** [comment]
Ugh. You're totally right.

Ok, key items to hide:
- seat held
- yes
- no
- precincts reporting
- runoff (i don't think we're displaying this?)
