### ISSUE TITLE
Inject custom CSS into the big board (and liveblog?) Seamus pages

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#140]
Very similar to the 2016 setup https://www.npr.org/include/overridecss/id500427835.css

We need more horizontal space than the Multimedia template gives us by default.

**Comment by alykat** [comment]
Saved here in the repo:
https://github.com/nprapps/elections18-graphics/tree/master/etc

Relevant utility commands that appear to generate the css files based on a template and the navbar spreadsheet:
https://github.com/nprapps/elections18-graphics/blob/master/fabfile/utils.py#L70-L97

```
fab utils.create_board_overridecss
fab utils.create_state_overridecss
```

**Comment by alykat** [comment]
Dependency: https://github.com/nprapps/elections18-graphics/issues/21

Once the new links are in the spreadsheet, we can generate the overridecss files.

**Comment by alykat** [comment]
This is done. Will need to regenerate / re-upload the css once we have the fallback text in place (#155), but otherwise I think this is good to go.
