### ISSUE TITLE
Style the poll-closing time on the state landing page

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#141]
Right now, poll-closing times are only shown if no votes are present yet. They were being rendered underneath the state descriptions on the state landing page (but those have been removed).

To see them (with our current test data that _already has_ votes), change

```
      areThereAnyVotesYet
        ? ''
        : h('p', `Polls closing at ${pollCloseTime} ET.`),
```

to

```
      h('p', `Polls closing at ${pollCloseTime} ET.`),
```

while you're designing, and just change it back once you're finished.

**Comment by alykat** [comment]
Done.

![image](https://user-images.githubusercontent.com/491318/46710095-73434200-cc14-11e8-844e-2926437e7924.png)
