### ISSUE TITLE
Board columns collide or overflow at narrow widths (especially with long names)

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#144]
<img width="560" alt="screen shot 2018-09-26 at 14 44 34" src="https://user-images.githubusercontent.com/4959135/46101761-bde7a780-c19a-11e8-815f-2d321f4a91d8.png">

See http://serendipity.drupal.publicbroadcasting.net/post/house-results-midterm-elections-test-2018#stream/0 on desktop. Although we should probably wait until the 2018 data comes (as you mentioned today!) to determine how spacing needs to work.

**Comment by mileswwatkins** [comment]
See also mobile-width state landing pages with long names:

<img width="400" alt="screen shot 2018-09-26 at 16 14 06" src="https://user-images.githubusercontent.com/4959135/46106703-74518980-c1a7-11e8-935d-0f8d2f8a75b2.png">

**Comment by mileswwatkins** [comment]
From KBIA:

> The one exception is on phones. Because of the way promo blocks have their padding and margin set up, the area for the graphic to fill on a Core Publisher site when it’s in a homepage on a phone is significantly narrower than it would be in any normal responsive view. For example, on an iPhone 6, the embed's viewport will only be 295px wide. 
 
> Right now, the text and charts overflow past this, making them unreadable on phones when they’re on a Core Publisher home page. Perhaps this means that there needs to be some sort of even more compact, mostly text and numbers based, view for super narrow positioning.

Screenshot:

![screen shot 2018-10-19 at 12 27 35 pm](https://user-images.githubusercontent.com/4959135/47297260-94c40680-d5e2-11e8-927f-0d75aa1db2e6.png)

**Comment by mileswwatkins** [comment]
From VPR, noting collision of the two columns at 485px:

<img width="507" alt="gov-485px" src="https://user-images.githubusercontent.com/4959135/47366537-e5ebfd00-d6ab-11e8-8286-d7d7a488f9a1.png">

**Comment by alykat** [comment]
Reworked the breakpoints so we shift to one-column mode a lot earlier (at 660px). Also hid first names earlier. The column unevenness still happens to a limited degree, but it's much improved and there hopefully are no collisions as bad as what you see in the screenshots above.

So this is what the gov board looks like at roughly 500px wide (about the size in the VPR bug report):

![image](https://user-images.githubusercontent.com/491318/47407503-859ba080-d729-11e8-9bdb-8a1308a96a8f.png)

And here's an example from the House board where there's still some column inconsistency, but it's all still much cleaner than before and nothing's overlapping poorly:

![image](https://user-images.githubusercontent.com/491318/47407537-b24fb800-d729-11e8-863c-9513ae3df56a.png)

**Comment by mileswwatkins** [comment]
It looks like this is mostly fixed, but long names in a couple state boards are still overflowing the views at 300px width:

<img width="313" alt="screen shot 2018-10-25 at 15 11 21" src="https://user-images.githubusercontent.com/4959135/47524468-b33b3380-d868-11e8-91e1-8d1a9b75167f.png">
<img width="318" alt="screen shot 2018-10-25 at 15 13 17" src="https://user-images.githubusercontent.com/4959135/47524469-b33b3380-d868-11e8-992b-e0e49d69b952.png">

**Comment by mileswwatkins** [comment]
The only other state with this problem is WI:

<img width="303" alt="screen shot 2018-10-25 at 15 20 46" src="https://user-images.githubusercontent.com/4959135/47524785-96ebc680-d869-11e8-8177-50004dce9980.png">

**Comment by alykat** [comment]
Ok let's try this again... :)

Candidates with last names > than 8 chars get a `transform:scale()` applied in CSS to compress them a bit. If they're still too long, then they'll get cut off. Still not great, but better than breaking the table?

![image](https://user-images.githubusercontent.com/491318/47587228-37a4b980-d930-11e8-8b2c-ef4ce3ba8b49.png)
