### ISSUE TITLE
Emphasize that upper-case surnames indicate incumbency

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#146]
This was confusing some of the member-station viewers, since the key just shows: `* INCUMBENT` next to a few other all-uppercase key items. Is there a way to make the key more expressive of this?

**Comment by alykat** [comment]
Changed the base typeface to Helvetica (instead of Gotham) and remove the default all-caps for everything. Hopefully this is a little clearer.

![image](https://user-images.githubusercontent.com/491318/47887536-4ef31380-de16-11e8-93ca-cfc4b99ba1b3.png)
