### ISSUE TITLE
Put graphics embeds into all Seamus pages

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#158]

**Comment by alykat** [comment]
This is not yet done -- got pushed back a little bit b/c of the added need for fallback text (#101) -- but current status:

- Embeds have been added to pages for the liveblog, all boards, and a few state pages (including AL and MN)
- Fallback text has been settled on.
- Bitly links have been created for all the fallback links.

Todo:
- Add remaining embeds to pages.
- Add fallback text + links to all pages.
- Check mobile override checkbox.

- All

**Comment by alykat** [comment]
Done! Thank you so much @goldfarb!
