### ISSUE TITLE
BOP/GCU: Independent label on the Senate bar has disappeared

### ISSUE THREAD

**Issue by alykat** [nprapps/elections18-graphics#160]
![image](https://user-images.githubusercontent.com/491318/46552658-5c65be00-c8a9-11e8-904e-95cfde7ba3d9.png)

**Comment by mileswwatkins** [comment]
I spotted the label just now floating to the far right of the GOP label (ie, off of the graphic entirely), when on `#fluid` width at 1400 px wide on `bop-gcu-liveblog`

**Comment by alykat** [comment]
Fixed

![image](https://user-images.githubusercontent.com/491318/47023121-f7258e80-d12c-11e8-9cd0-31559e779ca5.png)
