### ISSUE TITLE
Social-friendly version of Balance of Power

### ISSUE THREAD

**Issue by alykat** [nprapps/elections18-graphics#162]
For @reneeklahr to screencap during the night for use on social media. Renee will supply the header/footer.

**Comment by goldfarb** [comment]
![image](https://user-images.githubusercontent.com/3722037/48102226-1ed1b900-e1f8-11e8-9eaa-1d4c0f756dbd.png)

https://github.com/nprapps/elections18-graphics/commit/6911bc7bba9a824d642297e1b1ddebaa14619851
