### ISSUE TITLE
County names sometimes overflow their column on mobile tables

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#164]
I suspect this would be _possible_ when there're only two candidates in the table, but it's certainly happening when there're three. Here's an example from Kansas gubernatorial:

<img width="334" alt="screen shot 2018-10-10 at 18 12 11" src="https://user-images.githubusercontent.com/4959135/46768969-29ac3300-ccb8-11e8-91f2-178691d68844.png">

**Comment by alykat** [comment]
Better: 
![image](https://user-images.githubusercontent.com/491318/47336630-85829e80-d65e-11e8-8366-238fd853b098.png)

Also added a class to the table corresponding to the # of eligible candidates for that particular race (https://github.com/nprapps/elections18-graphics/commit/5051a9af3d94ffde406df7d6cfcbfa51cab9c835#diff-dabb8025e8c8d40a99ac2b2eaffa206cR449) allowing me to tailor the column widths a little more depending on the # of columns in the table.
