### ISSUE TITLE
State mini-big-board "detailed results" buttons have gray background

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#169]
On most browsers and devices outside of macOS Chrome, the "County-level results >" or "Detailed House results >" buttons have gray backgrounds. This includes iOS Safari, Android Chrome, and Windows 10 Edge. Eg:

<img width="386" alt="screen shot 2018-10-11 at 11 18 08" src="https://user-images.githubusercontent.com/4959135/46815409-e1892100-cd48-11e8-8e98-518f9c358a4e.png">

<img width="546" alt="screen shot 2018-10-11 at 11 07 33" src="https://user-images.githubusercontent.com/4959135/46815418-e51ca800-cd48-11e8-9595-757ae3889ef2.png">

<img width="562" alt="screen shot 2018-10-11 at 11 25 40" src="https://user-images.githubusercontent.com/4959135/46815443-ed74e300-cd48-11e8-938c-95b55c49bcf9.png">

**Comment by alykat** [comment]
Gray backgrounds begone (hopefully!).

![image](https://user-images.githubusercontent.com/491318/47089016-dc671e80-d1ed-11e8-9482-9ccc9dc8f44e.png)
