### ISSUE TITLE
Add credit

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#17]

**Comment by mileswwatkins** [comment]
@alykat, do you think that we should have a credit footer on these graphics?

For reference, NPR _didn't_ in 2016, but did in 2014:

<img width="556" alt="screen shot 2018-08-21 at 14 28 26" src="https://user-images.githubusercontent.com/4959135/44421440-7d1ec200-a54e-11e8-8434-33acfa3061c4.png">

NYT currently gives credit at the bottom of its 2018 results:

<img width="1014" alt="screen shot 2018-08-21 at 14 24 24" src="https://user-images.githubusercontent.com/4959135/44421462-90ca2880-a54e-11e8-9702-bfa452276b66.png">

WaPo does not have credits or bylines on their 2018 elections graphics

**Comment by alykat** [comment]
Since there's not one single URL for all of this, there's a question of where we should put it. Maybe under the liveblog?

**Comment by mileswwatkins** [comment]
The big boards already have a footer that we could attach to:

<img width="499" alt="screen shot 2018-08-24 at 13 25 29" src="https://user-images.githubusercontent.com/4959135/44598498-3248b880-a7a1-11e8-8a9d-38305f26485c.png">

And we could put something similar on the state results page (which already has a long footnote). If anything, I think it's fine to exclude an NPR Vis credit from the liveblog, since that's mostly editorial content (albeit wrapped in a tool that took a lot of Vis elbow-grease to build). Also, the bottom of the liveblog is going to be waaaaay down there ;)

**Comment by alykat** [comment]
FWIW, that footer is part of the Seamus page, not the big board embeds. But it seems repetitive to have our names at the bottom of every single page.

**Comment by mileswwatkins** [comment]
Aly:

> i'm inclined to leave them off. above the footer makes sense, but it feels really repetitive to have them them on every single page. and there's no one page (other than at the bottom of a very long liveblog) that makes sense.

**Comment by mileswwatkins** [comment]
Won't do
