### ISSUE TITLE
BoP "net gain" party "sticks" when a party goes from +1 to 0

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#172]
On BoP, when no party has gained seats for a chamber, we'd like to show:

<img width="387" alt="screen shot 2018-10-11 at 13 44 52" src="https://user-images.githubusercontent.com/4959135/46823462-41d58e00-cd5c-11e8-83e7-63f59e42ead1.png">

However, if a party goes from +1 to 0 while the graphic is open, then that party "sticks," and the graphic will read something like this (after GOP went from 1 pickup to 0 pickups):

<img width="218" alt="screen shot 2018-10-11 at 13 36 07" src="https://user-images.githubusercontent.com/4959135/46823497-59ad1200-cd5c-11e8-90d4-96cae17f975d.png">

For example, this is the JSON that resulted in the above:

<img width="427" alt="screen shot 2018-10-11 at 13 36 42" src="https://user-images.githubusercontent.com/4959135/46823519-67fb2e00-cd5c-11e8-9fa9-0093ecefd3e1.png">

**Comment by mileswwatkins** [comment]
Refreshing the webpage results in going back to the normal, gray "0" net gain box.

**Comment by alykat** [comment]
Saw this again during testing today. Reopening.

![image](https://user-images.githubusercontent.com/491318/47308032-81bf2f80-d5fe-11e8-8836-4d86f7c0ac62.png)
