### ISSUE TITLE
Runoff label very small in some circumstances

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#173]
When I use the `#fluid` container width in my macOS Chrome browser, the runoff label appears at a normal size with a full-width (~1400px) window, but when the window is very narrow (~400px?) then the runoff icon shrinks dramatically.

<img width="394" alt="screen shot 2018-10-11 at 14 34 49" src="https://user-images.githubusercontent.com/4959135/46826135-36d22c00-cd63-11e8-8c5d-ee59f89e78ca.png">

To be fair, when I use the `#desktop` or `#mobile` widths, the runoff icon doesn't show up _at all_.

**Comment by goldfarb** [comment]
![image](https://user-images.githubusercontent.com/3722037/47670419-7ed6b880-db83-11e8-8c6d-4325cb386b1d.png)

https://github.com/nprapps/elections18-graphics/compare/bcb1eb6c5876...af418b04d36f

Made changes to constrain the size of the *run/off* image

(it is easy to make it a single size if that's better, right now it is a small range of sizes)
