### ISSUE TITLE
Rebalance House board

### ISSUE THREAD

**Issue by alykat** [nprapps/elections18-graphics#178]
Possible to move 1 or 2 races over to the right column? It'll help more of the board fit into a single screen.

![image](https://user-images.githubusercontent.com/491318/46966389-a2760b00-d07b-11e8-819e-df1178355592.png)

**Comment by mileswwatkins** [comment]
We'll have fewer races when we finally launch, closer to 40–50 than 60+.

**Comment by alykat** [comment]
Related: #153

**Comment by mileswwatkins** [comment]
House before:

<img width="1373" alt="screen shot 2018-10-23 at 16 57 59" src="https://user-images.githubusercontent.com/4959135/47390214-d1782680-d6e4-11e8-9288-c47feb3986f1.png">

House after:

<img width="1295" alt="screen shot 2018-10-23 at 16 56 42" src="https://user-images.githubusercontent.com/4959135/47390164-b9080c00-d6e4-11e8-9bd8-1e580f2c1c2e.png">

and it works well with the other existing two-column boards as well.
