### ISSUE TITLE
Senate board: No percentage shown for Sanders

### ISSUE THREAD

**Issue by alykat** [nprapps/elections18-graphics#179]
Is this an Ind/Other issue? Looks like there's an `::after` style that isn't being applied.

![image](https://user-images.githubusercontent.com/491318/46966902-fa614180-d07c-11e8-9edc-dbac68a47588.png)

**Comment by alykat** [comment]
Yeah, now I can't replicate it. One difference I did note before I refreshed the page: The `<tr>` for VT-Sen only had an `.updated` class, not a `.reporting` class (which is what the CSS is looking for to append the %). But looking at the JS, `.updated` is just being added/removed from the `classList` — not replacing what's already there. So I'm stumped.

**Comment by mileswwatkins** [comment]
We haven't experienced this for a while; going to close.
