### ISSUE TITLE
IE 11 renders a big horizontal gap on the state pages

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#186]
<img width="774" alt="screen shot 2018-10-18 at 13 30 06" src="https://user-images.githubusercontent.com/4959135/47172642-0f86dc00-d2da-11e8-95fd-60e719ff6467.png">

(See me for credentials to BrowserStack)

**Comment by goldfarb** [comment]
removed `min-height` from board.less

- https://github.com/nprapps/elections18-graphics/commit/2b81da0cff20e5fad4a80f500e991a206285c526


![image](https://user-images.githubusercontent.com/3722037/47306281-f9d72680-d5f9-11e8-8814-717ec5c71a61.png)
