### ISSUE TITLE
Mobile navbar: Change "View Results" to "All News And Results"

### ISSUE THREAD

**Issue by alykat** [nprapps/elections18-graphics#191]
Alternate option: "More Live Results"

Will need to be changed on graphics and on the liveblog.

**Comment by mileswwatkins** [comment]
Will just need to be changed in one location (the graphics repo), since that HTML is loaded by the liveblog.

**Comment by alykat** [comment]
"More Live Results" seemed to fit best in the smallest width we design for (300px).

![image](https://user-images.githubusercontent.com/491318/47276492-46344f00-d585-11e8-949c-cedaabd9c096.png)

**Comment by alykat** [comment]
"More Live Results" seemed to fit best in the smallest width we design for (300px).

![image](https://user-images.githubusercontent.com/491318/47276492-46344f00-d585-11e8-949c-cedaabd9c096.png)
