### ISSUE TITLE
Ballot big board rows on mobile may have differing column widths

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#192]
![image 1](https://user-images.githubusercontent.com/4959135/47242049-a9728580-d3bb-11e8-83f2-83a4f067ee0c.png)

Perhaps this is due to them being two "different" columns from the two-col desktop layout? An uninformed guess from my end.

**Comment by mileswwatkins** [comment]
Never mind, it looks like this is _still_ happening on those devices in two-column layout. This is from an iPhone 6's Chrome:

![image from ios](https://user-images.githubusercontent.com/4959135/47242195-09692c00-d3bc-11e8-9d3b-30e75c3022f9.png)

**Comment by alykat** [comment]
I think this is no longer an issue.

![image](https://user-images.githubusercontent.com/491318/47462063-57ad6f00-d7b0-11e8-8a2a-8baf0a226a2d.png)
