### ISSUE TITLE
Set all Seamus pages to auto-publish at a specific time

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#194]
6 or 7 AM on election day was the plan, but we're going to bounce this off of the SEO team.

**Comment by mileswwatkins** [comment]
Here's the publishing plan https://docs.google.com/spreadsheets/d/14waWMjfyiGUPGNlOJ4X8_KaFUsRI9OmaLAIyDjGCueY/edit?ts=5bca2843#gid=694283294

**Comment by mileswwatkins** [comment]
Cleared for 7 AM for all pages.

**Comment by mileswwatkins** [comment]
Dana and Aly will set this up on Monday

**Comment by alykat** [comment]
Done.
