### ISSUE TITLE
Display poll close times (or expected first results times) on state results pages

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#2]
From @alykat in 2016:

> If there's no call or votes, show the poll closing time. If there's a call or votes, then show the results table.

cc https://github.com/nprapps/elections16graphics/issues/185

**Comment by mileswwatkins** [comment]
We can also use the "expected first results" information instead, or in addition.

**Comment by mileswwatkins** [comment]
Displaying expected-first-results time is a low priority. Should we even display poll-close times on the state pages at all?

**Comment by alykat** [comment]
This is useful but not essential.

Low-lift possibility: We display the poll closing (and/or results expected) times in text under the briefing book write-ups and leave it at that.

**Comment by alykat** [comment]
Related question: Should we attempt to localize any time-based display? Historically, we've standardized on ET. But that might be weird when embedded on station sites.

**Comment by mileswwatkins** [comment]
Arnie:

> Since stations will have the state pages, and serve much more of a community service, we should find somewhere to indicate poll close times

And in response to your point @alykat, I think it's definitely worth it to look into level-of-effort for time localization, given the member station embedding.

**Comment by mileswwatkins** [comment]
If there are no results in yet, we'll show poll-close time:

<img width="487" alt="screen shot 2018-08-27 at 17 10 12" src="https://user-images.githubusercontent.com/4959135/44686406-1bfa6100-aa1c-11e8-8846-f5ff264e529f.png">
