### ISSUE TITLE
State results: County names for New England states are all-caps, while other states are Upper/Lower

### ISSUE THREAD

**Issue by alykat** [nprapps/elections18-graphics#201]
Massachusetts:

![image](https://user-images.githubusercontent.com/491318/47336512-160caf00-d65e-11e8-9af8-83696f7f8ced.png)

Kansas:
![image](https://user-images.githubusercontent.com/491318/47336526-2a50ac00-d65e-11e8-8691-7b26a6eaee47.png)

**Comment by mileswwatkins** [comment]
Good catch. This is coming out of Elex, which converts New England towns (from the AP API) to New England counties, and upper-cases all the county names.

https://github.com/newsdev/elex/blob/9ec4af6bdf9bcbdacec31f4a2ba18265e7093fe7/elex/api/maps.py#L5

I submitted a PR against Elex just now, but I don't think it'll get merged and deployed to a new version on PyPI before election day. In the meantime, we can apply title-casing to New England counties on the front-end; none have internal capitalization.
