### ISSUE TITLE
Board elements on narrow Seamus multimedia views have no side-padding

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#208]
There's no room on the left or right; the following screenshot has lines and characters touching the left edge of the window, for example:

<img width="546" alt="screen shot 2018-10-25 at 17 01 05" src="https://user-images.githubusercontent.com/4959135/47530100-a8d46600-d877-11e8-843c-013c5ac0262d.png">

**Comment by alykat** [comment]
Hopefully fixed for real in a66c2e31641b6f018b0df53add453357190aef17
