### ISSUE TITLE
Create Seamus pages

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#21]
[Instructions from 2016 for creating each state page](https://docs.google.com/document/d/1sRL-WuzzqbHUeeAp71Y4l2UW7D7mYRygCMHG_J9CLZ8/edit#heading=h.hdffs58q3uw5)

**Comment by mileswwatkins** [comment]
This will also entail updating the nav spreadsheets, so that the populated templates know what to link to:

- https://docs.google.com/spreadsheets/d/1Eqp-jei3xFMpUOFJFuMHk8zP8WSGtvCwoo1a21vtloo
- https://docs.google.com/spreadsheets/d/1pfTPmeWGTQlw_7efXcnMoblarzyaz_zjDzqBfLFnLYg

**Comment by alykat** [comment]
Related resources:

From 2016, detailed instructions for how to create a results page in Seamus (we would want to make an updated version for 2018, including info for the iOS workaround):
https://docs.google.com/document/d/1sRL-WuzzqbHUeeAp71Y4l2UW7D7mYRygCMHG_J9CLZ8/edit#

Promo images for each state:
https://drive.google.com/drive/folders/0B2a8I_ZarNfGdzRTV0kydG1pNGM

(Would still need to identify/make promo images for the boards. Will assume that the Politics and Engagement teams will handle promo images for the liveblog.)

**Comment by mileswwatkins** [comment]
Dana is owning this page-creation, and aiming to be finished by the end of the first week of October.

**Comment by mileswwatkins** [comment]
Dana's adding these for all pages, as she builds out:
- headline
- teasers
- bylines
- topics
- making them multimedia pages
- preview image
- _putting the Seamus ID into the Google Sheet that powers the navbar_

Remaining after that:
- fallback text (ticketed separately)
- overridecss (ticketed separately)
- promo image for liveblog or big boards (Dana's still deciding on these)

**Comment by mileswwatkins** [comment]
All Seamus pages have been created!

**Comment by mileswwatkins** [comment]
cc https://github.com/nprapps/elections18-graphics/issues/157

**Comment by mileswwatkins** [comment]
cc https://github.com/nprapps/elections18-graphics/issues/158
