### ISSUE TITLE
Color-code 2016-presidential-margin text on the county tables, by party

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#212]
So that it has a similar pattern to the current-margin text

<img width="804" alt="screen shot 2018-10-29 at 14 55 42" src="https://user-images.githubusercontent.com/4959135/47674799-894a7f80-db8e-11e8-8cdb-1da2a9c1c406.png">

**Comment by goldfarb** [comment]
![image](https://user-images.githubusercontent.com/3722037/47738096-cb37fc00-dc48-11e8-8550-4de33ddbac8d.png)

![image](https://user-images.githubusercontent.com/3722037/47738122-d854eb00-dc48-11e8-89f2-2a60be97b23c.png)

Gave the presidential margin column color.

https://github.com/nprapps/elections18-graphics/commit/7770254200e2f420bc94f2203b6b79c83c4ac5a9
