### ISSUE TITLE
Update state summaries, largely based on briefing book

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#22]
[Here's 2016's spreadsheet](https://docs.google.com/spreadsheets/d/1cG6itV9fK9Fc7AA_On4ToUgqEWA8Ae5bp0JCxQdtEOw/edit#gid=0)

Domenico will be providing these, altered from the briefing book. These'll be present for _all_ states. Timeline being decided by Arnie and Beth this week. Eg from 2016:

<img width="751" alt="screen shot 2018-07-31 at 09 55 26" src="https://user-images.githubusercontent.com/4959135/43463961-e0d2b44e-94a7-11e8-9381-bd3d6aea4b1f.png">

**Comment by mileswwatkins** [comment]
The blurbs need to be listed in [this Google Sheet](https://docs.google.com/spreadsheets/d/1zrWMnfdu36I3axyubc8p9ZmNBwS1o-GlmHXHky5EySA)

**Comment by mileswwatkins** [comment]
> The info blurbs we can absolutely have done by Oct 1 because we will need to have the briefing book printed by then.

**Comment by mileswwatkins** [comment]
The briefing book deadline is now September 20. Another thing that'd be helpful is to provide Domenico a _character limit_ so that he knows the maximum length the text can be while still not taking up the entire above-the-fold area on mobile.

**Comment by mileswwatkins** [comment]
Uhh, ballpark 400–600 character max? We can revisit when we need to tell Domenico.

**Comment by alykat** [comment]
I'd say a ballpark of 80 words / 500 chars? On mobile, that would allow some of the results to be visible on the screen w/o scrolling. 

![image](https://user-images.githubusercontent.com/491318/45497457-db9e2100-b745-11e8-8943-55a42302f425.png)

**Comment by mileswwatkins** [comment]
We're not using these, per conversation with Arnie and Dana today.
