### ISSUE TITLE
Add 2016 Trump margin as sort variable on county tables

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#34]
_Remove_ the 2012 Obama-lead percentage, too!

**Comment by mileswwatkins** [comment]
Make sure to credit the data source at the bottom of the `renderMaquette` in `www/js/state-results.js`.

**Comment by freejoe76** [comment]
Example URL (prod) https://www.npr.org/2016/11/08/499666514/pennsylvania-2016-presidential-and-state-election-results

**Comment by freejoe76** [comment]
Per Miles suggestion I'm looking into non-AP sources for 2016's county-level presidential election results. So far: the FEC's official results ( https://transition.fec.gov/general/FederalElections2016.shtml ) only go down to the state level, and there are javascript issues on OpenElections' results URL ( http://www.openelections.net/results/ ) that are keeping the download URLs for its data from rendering.

I've done research on OpenElections' github in service of finding its county-level information, I've started tracing back in its javascript to figure out the CSV / JSON download URL pattern. That looks like our best chance.

**Comment by freejoe76** [comment]
Update: OpenElections' data on 2016 presidential results exists for a few states. I'm looking at if all the post-election coverage used AP's night-of numbers.

**Comment by freejoe76** [comment]
Okay, so I merged with master before I did the parts on the front-end interface, I realized just now.

**Comment by freejoe76** [comment]
This is finished.

**Comment by freejoe76** [comment]
To see these changes from, say, http://localhost:8000/state-results/?state=ky :

1. Click the "county-level results" button under the "Senate" header.
2. Look down to the Results By County header.

![screen shot 2018-08-22 at 12 03 31 pm](https://user-images.githubusercontent.com/125554/44481681-b402df80-a603-11e8-80c2-ce503a00e5ea.png)
