### ISSUE TITLE
Design main balance-of-power graphic

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#37]
If this is going to be more than the BoP before-and-after bar chart from 2016, we should figure out what it is. This design will be undertaken during the development sprints, not during the earlier design phase.

**Comment by alykat** [comment]
Possible D3 prior work we can reference if we want to go with a "Parliament Chart"-style visualization:

http://bl.ocks.org/gka/515a041815df4c37d659
https://github.com/geoffreybr/d3-parliament

**Comment by mileswwatkins** [comment]
Our plan is to generally re-use the previous elections' bar chart, with emphasis on pickup numbers.
