### ISSUE TITLE
Create the "Get Caught Up" graphic

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#48]
This graphic will be a box that is curated/updated regularly by the Washington desk. It will contain a set of bullets with prose that includes deep links to the liveblog and/or links to Seamus pages.

- [x] Work with that desk to determine what the best format will be for input; the graphic will likely read from Google Sheets, but should it read from a single cell of content, or should each bullet point be a separate cell?
- [x] Create a static version of the embed, unstyled
- [x] Style the graphic, based on Aly's wireframes and other existing style choices
- [x] Piggyback on an existing rendering process to generate/regenerate this graphic on-the-fly, based on the contents of that Google Sheet (or other source)

This graphic will live as a standalone widget, or side-by-side with balance of power and other graphics.

<img width="351" alt="screen shot 2018-07-31 at 13 57 47" src="https://user-images.githubusercontent.com/4959135/43477638-bb4e9324-94c9-11e8-926c-07530f449140.png">

**Comment by mileswwatkins** [comment]
@freejoe76: Amita Kelly was the point person (on the editorial/non-tech side) for this text area in 2016. And Nicole Hernandez was (or at least knows) who was in charge of this field during [the liveblog of the 2017 eclipse](https://www.npr.org/sections/thetwo-way/2017/08/21/544239796/live-coverage-follow-the-solar-eclipse).

**Comment by freejoe76** [comment]
Note that Miles last week received information that whoever is in charge of administering this in Google Sheets *can* be trusted to write link markup.

**Comment by freejoe76** [comment]
@mileswwatkins The part that I'm vague on now, here, is how this graphic will be placed and who makes the call where it goes -- do you have an idea on that?

**Comment by mileswwatkins** [comment]
> how this graphic will be placed

Hmm, what do you mean by that? After doing some more work with the graphics, I'm envisioning that the data for this graphic will be pulled from Google Sheets to a JSON or HTML file by the back-end repo (in its `fabfile/render.py`), and then that data (or HMTL) will be loaded into a template and rendered by the front-end repo (by adding `less/get-caught-up.js` and `www/js/get-caught-up.js`, which'll be built alongside all other `www/js/*.js` files by webpack).

Let me know if that answers the question! Happy to pair on this, too, if you're still getting your bearings on this workflow/pipeline. And also happy for you to suggest a better way to do this :)

**Comment by freejoe76** [comment]
Hmm so right, those are the nuts and bolts that get it to the web, but the part I'm vague on is what would be the URL(s) it shows up on, and where on that/those URL(s) would it appear, and how is that part managed?

**Comment by mileswwatkins** [comment]
The actual placement of the get-caught-up graphic onto the page will be in the contexts laid out by @alykat in this diagram, always alongside the balance-of-power graphic:

https://drive.google.com/drive/u/1/folders/16RZSrOHgkA3fqyf_ziIg_KGplwKDEo2y

It'll be a Pym.js `<iframe>` embed. Potentially it'll be a _nested_ embed, if we need to coordinate its placement alongside other elements:

- https://github.com/nprapps/elections18-graphics/issues/47
- https://github.com/nprapps/elections18-graphics/issues/52

**Comment by freejoe76** [comment]
Okay, now it makes sense end to end, thank you Miles, the iframe part was the info I was looking for.

**Comment by alykat** [comment]
Since these are being built w/in the context of the graphics repo and not the liveblog repo, hopefully we can combine these in the same embed and won't have to nest.

**Comment by freejoe76** [comment]
Note that there's now a way to render the json data file for get-caught-up, in elections18-general, `fab render.render_get_caught_up`

**Comment by freejoe76** [comment]
![screen shot 2018-09-05 at 1 00 11 pm](https://user-images.githubusercontent.com/125554/45112182-91e18500-b10c-11e8-9de8-d50f6d2356d4.png)

**Comment by freejoe76** [comment]
I just realized: Links written in the Get Caught Up google sheet will need to either have `target="_top"` already written into them, or added to them. Otherwise clicking the link will open the link within that iframe.

I'm inclined to parse out the links on the backend and add `target="_top"` where it doesn't exist already.

**Comment by freejoe76** [comment]
Also, @alykat, is this what you want the Get Caught Up graphic to look like?

https://user-images.githubusercontent.com/4959135/43477638-bb4e9324-94c9-11e8-926c-07530f449140.png

Because it currently looks more like

![screen shot 2018-09-06 at 5 10 16 pm](https://user-images.githubusercontent.com/125554/45186381-4b1e8880-b1fb-11e8-9d00-13593da6e3b8.png)

**Comment by mileswwatkins** [comment]
> I'm inclined to parse out the links on the backend and add target="_top" where it doesn't exist already.

Sounds good to me, @freejoe76!

And don't worry too much about hitting the initial designs; we can improve the styling later. I believe what you linked to is a wireframe, so not styled.

**Comment by alykat** [comment]
Yeah, no worries — I'll handle styling.

Re: popping up links:

1) The base template is already set up to do `target="_top"` by default: https://github.com/nprapps/elections18-graphics/blob/master/templates/_base_child.html#L12

2) In 2016, we had code in place where, when links pointed to URLs on NPR.org, the parent page would reload via PJAX in a way that wouldn't disrupt the persistent audio player.

Some of that we still have:

- Embed code: https://github.com/nprapps/elections18-graphics/blob/master/templates/_base_parent.html#L183-L190

- Navbar: https://github.com/nprapps/elections18-graphics/blob/master/www/js/includes/navbar.js#L22-L34

We could consider adding it for the liveblog headlines:

- https://github.com/nprapps/elections16graphics/blob/master/www/js/map-liveblog-hp.js#L35-L48

**Comment by freejoe76** [comment]
Per Arnie, via Miles:
>>> - for safety: use a `published` row (if its value isn’t `yes`, then don’t publish the JSON file), have that validator column to help editorial staff debug markdown issues, and have a HTML validator on the back-end to also confirm that the markdown is good (there must be a good Python HTML validator)

**Comment by mileswwatkins** [comment]
Documentation here: https://docs.google.com/document/d/1r9bTEv0xeeOoywahBUFtE2vXIuQK_vOKTSIgJTliODI

**Comment by mileswwatkins** [comment]
Documentation is loosely good to go, we can edit/improve it as we do testing.
