### ISSUE TITLE
Build homepage embed

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#52]
Construct the homepage election-visuals block, based on elements that've been ticketed out elsewhere.

Layout from wireframe:

<img width="570" alt="screen shot 2018-07-31 at 16 09 38" src="https://user-images.githubusercontent.com/4959135/43484363-25078e3a-94dc-11e8-849b-6b9dca15ae0b.png">

**Comment by mileswwatkins** [comment]
Question: does the "follow live coverage" block need to contain dynamic text?

**Comment by alykat** [comment]
It's not something that will live in the embed. "Follow Live Coverage" and the text below would be edited in Seamus and maintained by the homepage editor.

**Comment by mileswwatkins** [comment]
<img width="743" alt="screen shot 2018-10-05 at 12 35 06" src="https://user-images.githubusercontent.com/4959135/46547863-5072ff80-c89b-11e8-9a84-36a8f91ce3a9.png">

(bop graphic cropped out of my screenshot)
