### ISSUE TITLE
Update state-page nav, so that there's a landing page and one page per race-type

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#54]
Check for layout issues on mobile, especially. Also, handle cases where there's a special election (and thus more than one Senate race)!

**Comment by mileswwatkins** [comment]
Question for you, @alykat: Do we need to be able to deep-link into these race-type tabs?

**Comment by alykat** [comment]
Definitely yes if we want to link races on the big boards (https://github.com/nprapps/elections18-graphics/issues/41). And I can see it being useful if a particular senate/gov race becomes particularly heated and we want to promote county-level results.

I'd say yes, but normal-pri?
