### ISSUE TITLE
Update graphics embed code to use npr-pym-loader

### ISSUE THREAD

**Issue by alykat** [nprapps/elections18-graphics#60]
What we're currently using in dailygraphics is much simpler. For example:

```
<p data-pym-loader data-child-src="https://apps.npr.org/dailygraphics/graphics/theater-top2018-20180730/child.html" id="responsive-embed-theater-top2018-20180730">Loading...</p><script type="text/javascript" src="https://pym.nprapps.org/npr-pym-loader.v2.min.js"></script>
```

We should evaluate whether doing this will break the the PJAX navigation code, though. (This code is used to make clicking from page to page work more smoothly and not disrupt the audio player.) Take a look at the most recent liveblog code to see how it handles this.

**Comment by mileswwatkins** [comment]
@alykat, would you feel comfortable tackling this ticket (along with https://github.com/nprapps/liveblog/issues/33)?

**Comment by mileswwatkins** [comment]
cc https://github.com/nprapps/elections18-graphics/commit/58773bb7f282d7b689fc1e425e2feeb22f52e7fb

**Comment by mileswwatkins** [comment]
Tyler said:

> i remember having to do all [the special npr.org-specific embed JS] so that navigating between the special iframe only pages would work correctly

> a link from _within the iframe_ to another seamus page did not correctly call seamus's PJAX stuff

He also noted:

> testing on seamus staging should turn up any issues that would show up on prod

I'm going to put this on the back burner, at least until I hear from Juan whether this is simply a Seamus convenience improvement, or if there're larger benefits to unifying the embed codes.

Joe already updated the codes from Pym v0 to v1, and Aly upgraded prod to HTTPS, so that should cover most low-hanging functionality improvements otherwise.

**Comment by alykat** [comment]
Benefits of doing this:
- Simpler embed code
- We're using the same embed code that stations are using
- In the rare event that a (non-Core Publisher) station gets our embed via the API and displays it, they'll get the cleaner embed code that would be more likely to successfully render, rather than the thicket of inline JS.

With the liveblog, when we moved to the universal embed code (w/ the loader), stations got to take advantage of features like permalinks to liveblog entries b/c the supporting code for that was wrapped into the loader. See:
http://www.wesa.fm/post/follow-solar-eclipse-nprs-live-blog?post=a-silver-lining-in-some-of-the-clouds-50#stream/0

For the election graphics, I think the only special thing we're doing involves the navbar and PJAX navigation, and that's only for NPR.org. I think we probably could take the liveblog loader, remove  code re: permalinks and lazy-loading, and go from there.

**Comment by mileswwatkins** [comment]
Juan chimed in:

> There are not many advantages if the code still works....having only one embed allows you to simplify. Pjax should be handled directly on the loader and only for NPR if I recall correctly...
> And you have the option of using visibility or scroll tracking using the new loader without too much boilerplate....
> But as said not much to gain if you have working code already
