### ISSUE TITLE
Show a check-mark in the BoP chart when a _chamber_ has been called

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#65]
If we're using bar charts, add a check-mark once a party has control of a chamber

**Comment by mileswwatkins** [comment]
Arnie:

> 50/50 should have a check mark for GOP control

**Comment by alykat** [comment]
Screenshot: https://drive.google.com/open?id=16WW69SNaojlm2v_87Qm1epiMGGNIOK0D
