### ISSUE TITLE
Create a liveblog guide and training

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#7]
Similar to [the Eclipse liveblog guide](https://docs.google.com/document/d/1UhahzMqFfYJDNoETCeYgJlAJVC4R-mnpPA-8Vfh3jYs/edit#)

**Comment by lindamood** [comment]
here's the [2016 election liveblog documentation](https://docs.google.com/document/d/1I_CEuDi8NvuaMmJljjeZWyEf0nvWm3Qih3pm7uBCANw/edit)

**Comment by mileswwatkins** [comment]
As I read through the docs, it seems like this aspect of the workflow will have to be updated to lean more heavily outside of Visuals; we won't have extra staff to make liveblog additions from incoming emails:

![image12](https://user-images.githubusercontent.com/4959135/42645847-18019ad2-85cd-11e8-91ef-8ed6106be470.png)

**Comment by mileswwatkins** [comment]
Updated the 2016 elections slash 2017 eclipse training!

https://docs.google.com/document/d/1ewEUH0FZbNh8bvu0Xlb302Ksh6kgh7h1mJe_wcOCeD4/edit#

**Comment by mileswwatkins** [comment]
And running the training at noon today.
