### ISSUE TITLE
Design chamber balance-of-power bar chart

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#71]
The plan is to generally re-use the previous elections' bar chart, with emphasis on pickup numbers.

cc https://github.com/nprapps/elections18-graphics/issues/37#issuecomment-411208779

**Comment by mileswwatkins** [comment]
Splitting this into separate design and dev/build tickets.

**Comment by alykat** [comment]
Current thinking:

_(side-by-side view)_

![image](https://user-images.githubusercontent.com/491318/44234818-80443780-a175-11e8-9aac-d61629d30022.png)
 
_(stacked/mobile view)_

![image](https://user-images.githubusercontent.com/491318/44234856-a4a01400-a175-11e8-8c16-371fa58b0a3f.png)

**Comment by alykat** [comment]
Ok, I think we're in a good place with this. Arnie has signed off. Latest comp here:
https://drive.google.com/open?id=1xf0DmccW_YOovndsb6aaynJHeP9rj7Aa
