### ISSUE TITLE
Update county tables to use the top two candidates for the given race

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#73]
Right now, they're hardcoded to the 2016 presidential candidates. They'll need to dynamically set to the top two Senate or Governor candidates for that state.

**Comment by alykat** [comment]
Related question: How do we define the top two before results come in? In most cases, it will probably be the D and R candidates, but not always. Worth looking at big board template logic?

**Comment by mileswwatkins** [comment]
Good thinking. I don't think we need anything besides hard-coded logic here, since competitive third-party candidates are so rare. There will only be Sanders and King, although I'll confirm with Arnie that this is also true for gubernatorial races.

cc https://github.com/nprapps/elections18-graphics/issues/50#issuecomment-409723309

**Comment by mileswwatkins** [comment]
cc https://github.com/nprapps/elections18-graphics/issues/50#issuecomment-412545819

> I have to look at the Gov races more closely. I would guess that there is a third party candidate somewhere that we’d need to address

**Comment by mileswwatkins** [comment]
Arnie is looking into third-party gubernatorial candidates, and will let us know by Wednesday Aug 15.

**Comment by mileswwatkins** [comment]
JSON files added here https://github.com/nprapps/elections18-graphics/commit/6ba23e3a09b801d4f570b641949cdb0c79173105

Also, cc'ing @freejoe76 on this Issue. @freejoe76: I'll close this issue as soon as I have the front-end county tables back up; this'll unblock you.

**Comment by mileswwatkins** [comment]
@freejoe76, you're unblocked: ![statewide-table](https://user-images.githubusercontent.com/4959135/44070444-e15fba88-9f51-11e8-95ee-4a97ce444142.gif)

**Comment by mileswwatkins** [comment]
This issue is mostly closed, but I still need to deal with:

- [ ] Check that this works with independent candidates (including correct coloring)
- [ ] What happens in the rare case where there are three competitive candidates? Arnie gave us one of these.
- [ ] Spot-check that the sorting is correct

**Comment by mileswwatkins** [comment]
The tables will include all non-`Other` candidates in the results JSON. This means that in the rare case we need three candidates, this will be supported by the front-end, as long as that third candidate isn't `collate_other_candidates`'d when rendering the JSON on the back-end.
