### ISSUE TITLE
Build chamber balance-of-power bar chart

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#75]
Per the design work from https://github.com/nprapps/elections18-graphics/issues/71

**Comment by alykat** [comment]
Suggestion from @freejoe76:

> One idea for the `D+2`-type pieces of information is to put that information in an `<abbr>` element, as in `<abbr title="Democrats have gained two seats, total">D+2</abbr>`, which would illuminate the additional information on desktop and screenreaders (though not handheld).
