### ISSUE TITLE
Conduct accessibility review, and identify fixes

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#77]
Around the same time we check for page performance (https://github.com/nprapps/elections18-graphics/issues/14), let's also check for accessibility and screen-reader compatibility. We can identify places where we're not using semantic HTML, alt tags, etc., and (depending on available staffing and progress so far) identify the low-hanging fixes to improve support.

**Comment by freejoe76** [comment]
I'm putting accessibility notes here for collation later into one place.

1. Use semantic elements when possible (i.e. `<footer class="npr-footer">` instead of `<div class="npr-footer">`)
2. Iframe elements should either have a descriptive title attribute, alternatively, the iframe'd document needs a descriptive title element.

**Comment by freejoe76** [comment]
TODO: Write descriptive title elements for each of the html files in templates/graphics/.

**Comment by freejoe76** [comment]
Resources:

Recommended ways of hiding elements from visual browsers while keeping them available to screen readers: https://www.nomensa.com/blog/2017/how-improve-web-accessibility-hiding-elements

Recommended accessible table markup: https://webaim.org/techniques/tables/data

**Comment by freejoe76** [comment]
Re: d901148, this is what the table looks like were the table header row *not* be hidden.

![screen shot 2018-09-06 at 3 13 03 pm](https://user-images.githubusercontent.com/125554/45179814-96c73700-b1e7-11e8-99e2-8b9c0c850771.png)

**Comment by freejoe76** [comment]
Some notes after going through the state-results pages using MacOs voiceover (more https://help.apple.com/voiceover/info/guide/10.12/ ):

* The state-faces font is read literally. The state of Kentucky is the letter "Q," it's read as such. A better solution would be to hide that element from screen readers.
* When states are published as abbreviations, i.e. "KY" for Kentucky, that abbreviation is read aloud "Kay Why." It's worth wrapping that text in an `<abbr>` element, like so: `<abbr title="Kentucky">KY</abbr>` or in the case of, say, "KY-6," `<abbr title="Kentucky, House district 6">KY-6</abbr>`
* Note that asterisks to denote incumbents are read literally. That asterisk is assigned via the css content property, which does not allow markup as part of that content. The fix to that, remove the CSS style content attribute and add this markup to each incumbent candidate-name table cell: '<abbr title="Incumbent">*</abbr>`
* This markup around the candidate in the results tables causes each word to be read separately and have to be navigated to separately. I thought wrapping that in a `<p></p>` would fix that, but I tried that and it didn't.
![screen shot 2018-09-07 at 2 41 19 pm](https://user-images.githubusercontent.com/125554/45237280-3948ee00-b2ac-11e8-87f1-d76fe292397b.png)

**Comment by mileswwatkins** [comment]
@alykat, we don't need `title` blocks on these graphics, right? Since they won't ever be the entirety of a page.

cc https://github.com/nprapps/elections18-graphics/commit/186c550d304d75982939459a2b5805774ca9a4c8

**Comment by mileswwatkins** [comment]
Remaining to do: handheld voiceover evaluation. I'm going to close this ticket, and spin that out as a separate (mid-priority) ticket. Will also spin out the issues @freejoe76 identified into new tickets as well.
