### ISSUE TITLE
Update county-table-width styling, now that it's less cramped

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#78]
Now that we only need to cram 2–3 candidates into the county tables (instead of 4 from 2016's presidential county tables), the spacing looks a little squashed, and so that component styling needs to be improved.

<img width="533" alt="screen shot 2018-08-14 at 10 26 25" src="https://user-images.githubusercontent.com/4959135/44097805-9ff90634-9fac-11e8-94dc-b99f3113c580.png">

<img width="960" alt="screen shot 2018-08-14 at 10 26 36" src="https://user-images.githubusercontent.com/4959135/44097809-a2da6230-9fac-11e8-9feb-03017aa0cee4.png">

**Comment by alykat** [comment]
Done. Desktop view:

![image](https://user-images.githubusercontent.com/491318/45660291-0087f080-bac6-11e8-89df-49b95207860a.png)

Mobile view:

![image](https://user-images.githubusercontent.com/491318/45660306-11d0fd00-bac6-11e8-844c-21abe73666b6.png)

**Comment by mileswwatkins** [comment]
Thoughts on leaving the county names all-uppercase? The AP gives them to us
all-lowercase, so we have no way to know of any internal capitalization.
(My back-of-the-envelope calculation is that ~50 of the ~3000 counties in
the US have internal capitalization in their names.)

**Comment by alykat** [comment]
Or we ditch AP's label text and use Census instead.

**Comment by mileswwatkins** [comment]
That would definitely be the ideal! Not sure if there's enough time to implement that.
