### ISSUE TITLE
Handle uncontested races in big board structure

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#82]
@alykat, if we're showing all House races in the landing-page view of the state pages, and using the big-board styling to present them, we'll have to handle the fact that some of those races are uncontested. What's the best way to handle that in the current visual paradigm? Once you decide, I can implement the JS logic, if need a bit of styling help :)

**Comment by alykat** [comment]
Assuming that the following holds true:
- AP doesn't tabulate uncontested races
- AP automatically calls uncontested races at poll closing time

Maybe let's do something like this (rough wireframe)?
![image](https://user-images.githubusercontent.com/491318/44161465-67f7ee00-a08b-11e8-9d90-42b888bc0973.png)

With a footnote at the bottom of the page explaining what uncontested means and why there's no vote data.

**Comment by mileswwatkins** [comment]
Spec filled

<img width="756" alt="screen shot 2018-08-18 at 11 41 39" src="https://user-images.githubusercontent.com/4959135/44300871-b7ccf400-a2db-11e8-9b5b-0628fed1c222.png">
