### ISSUE TITLE
Handle uncontested races in state-table structure

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#83]
Maybe we should replace `0` and `0%` in the table with `uncontested*`? @alykat, what do you think?

<img width="391" alt="screen shot 2018-08-16 at 09 55 06" src="https://user-images.githubusercontent.com/4959135/44212884-8c5ed380-a13a-11e8-9d96-2d1bd33964ef.png">

On the other hand, this is exactly how it was in 2016…

<img width="381" alt="screen shot 2018-08-16 at 09 58 06" src="https://user-images.githubusercontent.com/4959135/44213088-ec557a00-a13a-11e8-8144-32f1bcc74d16.png">

**Comment by freejoe76** [comment]
I vote "uncontested," fwiw.

**Comment by mileswwatkins** [comment]
<img width="579" alt="screen shot 2018-08-17 at 17 31 39" src="https://user-images.githubusercontent.com/4959135/44289708-6f61f780-a243-11e8-92b6-42af71c6a932.png">
