### ISSUE TITLE
Determine whether we handle House special elections

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#90]
There can be elections to fill the remainder of a currently-vacant House seat. For example, there was one in 2016 for Hawaii's First. They have a `racetype` that includes `"Special"`; in this case, `"Special General"`.

Should we just ignore these, for all our purposes? At the very least, we need to exclude them from our balance-of-power calculations.

**Comment by alykat** [comment]
I think historically we haven't treated them any differently. We do need to note what the most recent party control was for the BOP calculations. But double-check with Arnie.

**Comment by mileswwatkins** [comment]
@alykat looks like special US House races were ignored in 2016:

<img width="755" alt="screen shot 2018-08-20 at 13 30 23" src="https://user-images.githubusercontent.com/4959135/44356393-39a85300-a47d-11e8-834e-0eedde4b8123.png">

**Comment by mileswwatkins** [comment]
Confirmed with Arnie, we won't show these House specials.
