### ISSUE TITLE
Be able to call/project a chamber, for balance-of-power

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#92]
The AP (or we) may want to be able to _project_ a chamber before the number of _called_ seats reaches 50%+1. This may have to manifest in an admin panel switch, or integration with an additional AP data endpoint, or something else.

**Comment by mileswwatkins** [comment]
So, I looked through the API's `reports` endpoint set, and there _is no place_ where the AP makes a chamber-level call. The closest is the Trends report for a chamber, but that response is insufficient:

```
{
  "trendtable": {
    "office": "U.S. House",
    "OfficeTypeCode": "H",
    "Test": "0",
    "timestamp": "2016-12-11T03:18:54Z",
    "party": [
      {
        "title": "Dem",
        "trend": [
          {
            "Won": "194"
          },
          {
            "Leading": "0"
          },
          {
            "Holdovers": "0"
          },
          {
            "Winning Trend": "194"
          },
          {
            "Current": "188"
          },
          {
            "InsufficientVote": "0"
          }
        ],
        "NetChange": {
          "trend": [
            {
              "Winners": "+6"
            },
            {
              "Leaders": "0"
            }
          ]
        }
      },
      {
        "title": "GOP",
        "trend": [
          {
            "Won": "241"
          },
          {
            "Leading": "0"
          },
          {
            "Holdovers": "0"
          },
          {
            "Winning Trend": "241"
          },
          {
            "Current": "247"
          },
          {
            "InsufficientVote": "0"
          }
        ],
        "NetChange": {
          "trend": [
            {
              "Winners": "-6"
            },
            {
              "Leaders": "0"
            }
          ]
        }
      },
      {
        "title": "Others",
        "trend": [
          {
            "Won": "0"
          },
          {
            "Leading": "0"
          },
          {
            "Holdovers": "0"
          },
          {
            "Winning Trend": "0"
          },
          {
            "Current": "0"
          },
          {
            "InsufficientVote": "0"
          }
        ],
        "NetChange": {
          "trend": [
            {
              "Winners": "0"
            },
            {
              "Leaders": "0"
            }
          ]
        }
      }
    ],
    "InsufficientVote": {
      "trend": [
        {
          "Dem Open": "0"
        },
        {
          "GOP Open": "0"
        },
        {
          "Oth Open": "0"
        },
        {
          "Dem Incumbent": "0"
        },
        {
          "GOP Incumbent": "0"
        },
        {
          "Oth Incumbent": "0"
        },
        {
          "Total": "0"
        }
      ]
    }
  }
}
```

**Comment by mileswwatkins** [comment]
Arnie:

> On the last point, we should have an admin panel if AP won’t feed that data point, and probably even if they would. I think Beth and I should have an editorial convo with the AP folks in sept to see if they are going to characterize the chambers as called or not in wire copy. Then from there sort our process for making a call.

I'll probably push this work back to next week, so we have a bit more info. But this helps elucidate!

**Comment by mileswwatkins** [comment]
Hrm, I chewed over doing this (plus storing seat counts) in a new DB table, but it gets messy/nonstandard pretty quickly. Eg:

```
class ChamberResult(BaseModel):
    # This field relates to `Result.officename`, but since that is not
    # a primary key, we can't use `ForeignKeyField` here
    chamber = CharField(choices=(('U.S. House', 'U.S. House'), ('U.S. Senate', 'U.S. Senate')))
    seats_not_up_for_election = IntegerField()
    # Want to tie this to the `Calls` table, but that has a foreign key relationship to the `Results` table...

    def seats_total(self):
        if self.chamber == 'U.S. House':
            return 435
        elif self.chamber == 'U.S. Senate':
            return 100

    def tied_chamber_goes_to(self):
        # Want to select from an unrelated model, to determine who the vice-president is, but I don't think that's allowed in `peewee` properties
```

Two possibilities to investigate:
- Store chamber-win override as a new property within the `RaceMeta`
- Create a dummy `Result` entity, similar to the `national`-level Presidential result, that can store the override only

**Comment by mileswwatkins** [comment]
Also, more info from a chat with Arnie:
- if a chamber has 50%+1 race called, then automatically call the chamber; NPR will probably let this happen for the Senate
- should be able to both call _and_ remove that call
- we _will_ want this ability during presidential years
- this will _only_ appear in the big-board summary text, and the balance-of-power graphic
- Arnie or Domenico will own the admin panel and calls on election night

**Comment by mileswwatkins** [comment]
Issues with creating a dummy `Result`, as I'm trying that out:
- There's not a good way to inject extra JSON into the `elex results` parsing, so we have to go roundabout and create CSV rows to tack on to the `elex` output, before the `psql` ingest
- For presidential data, it's more natural to have an extra `US`/national-level `reportingunit`, but that doesn't carry over well to legislative chambers:
  - It's safe for now to fake candidate IDs (or leave them empty) for `Democrat` and `Republican`, but these IDs could be confusing+dangerous in the future
  - The chamber-level data would have to be a single-`reportingunit` race, since it couldn't be a national RU on any or all of the existing races (that'd break a good deal of assumptions)

So, this means that adding a `RaceMeta` attribute like `chamber_call_override` or something is the simplest way to inject this data into the system. Still yucky, though.

**Comment by mileswwatkins** [comment]
Admin panel and model component complete, now it just needs to propagate frontwards. Will work more on this after non-voter graphics.

![chamber-control-admin](https://user-images.githubusercontent.com/4959135/45165853-ae8cc400-b1c3-11e8-8c9e-731ee1810d76.gif)

**Comment by mileswwatkins** [comment]
Add an "are you sure?" confirmation, after calling.

**Comment by mileswwatkins** [comment]
cc https://github.com/nprapps/elections18-general/commit/52c1fcecfeb04db8d5dfab76978dc8eeaab2e12a

**Comment by mileswwatkins** [comment]
@alykat, does this data structure look good to power your balance-of-power on the front-end? I removed the `needed` and removed the `majority` (since majority is different in the Senate based on which party holds the VPOTUS seat), and added `chamber_control` (JSON value will either be `null`, `Dem`, or `GOP`):

```
{
  "senate_bop": {
    "total_seats": 100,
    "uncalled_races": 1,
    "last_updated": "Sept. 5, 2018, 5:23 p.m.",
    "chamber_control": "GOP",
    "Dem": {
      "seats": 46,
      "pickups": 2
    },
    "GOP": {
      "seats": 51,
      "pickups": -2
    },
    "Other": {
      "seats": 2,
      "pickups": 0
    }
  },
  "house_bop": {
    "total_seats": 435,
    "uncalled_races": 2,
    "last_updated": "Sept. 5, 2018, 5:23 p.m.",
    "chamber_control": "GOP",
    "Dem": {
      "seats": 194,
      "pickups": 6
    },
    "GOP": {
      "seats": 239,
      "pickups": -6
    },
    "Other": {
      "seats": 0,
      "pickups": 0
    }
  },
  "last_updated": "Sept. 5, 2018, 5:23 p.m."
}
```

**Comment by alykat** [comment]
For consistency w/ the other data, maybe `chamber_control` should be `npr_winner`? Also, do we need three instances of `last_updated`? Otherwise works for me.

**Comment by mileswwatkins** [comment]
Cool cool. `last_updated` is duplicated because it rolls up the most recent information datetime for each chamber. I don't think we use all three, though, so I'll trim to just the overall one!

**Comment by mileswwatkins** [comment]
Oh, and realized we need `last_updated` by chamber, for use on the single-chamber big boards.
