### ISSUE TITLE
Switch incumbency marker to something besides the italic `i`

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#98]
The existing `i` may be confused for "info" instead of "incumbent," at first glance. We should do some design exploration to try replacing it.

**Comment by alykat** [comment]
Did a quick survey of our peers and most folks seem to use an asterisk. For the boards, that's a bit hard to see at a distance, so I'm all-caps-ing the last name, too.

![image](https://user-images.githubusercontent.com/491318/45169038-bd2aa980-b1ca-11e8-99b3-8ef08184014e.png)

![image](https://user-images.githubusercontent.com/491318/45169206-185c9c00-b1cb-11e8-8e03-d7f131299b14.png)
